USE [AIDE]
GO

/****** Object:  StoredProcedure [dbo].[sp_GetComcellMeeting]    Script Date: 10/06/2020 18:17:08 ******/
DROP PROCEDURE [dbo].[sp_GetComcellMeeting]
GO

/****** Object:  StoredProcedure [dbo].[sp_GetComcellMeeting]    Script Date: 10/06/2020 18:17:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_GetComcellMeeting]
	-- Add the parameters for the stored procedure here
	@EMP_ID INT,
	@YEAR INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @DEPTID INT = (SELECT DEPT_ID FROM EMPLOYEE WHERE EMP_ID = @EMP_ID)
	DECLARE @DIVID INT = (SELECT DIV_ID FROM EMPLOYEE WHERE EMP_ID = @EMP_ID)
	DECLARE @FIRSTMONTH DATE, @LASTMONTH DATE

	-- Set Current Fiscal Year
	--SET @FIRSTMONTH = CAST('4/1/' + Cast(@YEAR as varchar) AS DATE)
	--SET @LASTMONTH = CAST('3/31/' + Cast(@YEAR + 1 as varchar) AS DATE)

	SET @FIRSTMONTH = (SELECT FY_START FROM FISCAL_YEAR WHERE YEAR(FY_START) = @YEAR)
	SET @LASTMONTH = (SELECT FY_END FROM FISCAL_YEAR WHERE YEAR(FY_START) = @YEAR)
	
    -- Insert statements for procedure here
	SELECT F.FIRST_NAME as FAC_NAME,
			MT.FIRST_NAME as MIN_NAME,
			CM.*,
			WR.WEEK_START 
	FROM COMCELL_MEETING CM
		Inner Join Employee MGR 
			On CM.EMP_ID = MGR.EMP_ID
		Inner Join EMPLOYEE F
			On CM.FACILITATOR = F.EMP_ID
		Inner Join EMPLOYEE MT
			On CM.MINUTES_TAKER = MT.EMP_ID
		Left  Join WEEK_RANGE WR
			On CM.[WEEK] = WR.WEEK_ID
	WHERE MGR.DEPT_ID = @DEPTID 
		And MGR.DIV_ID = @DIVID
		And FY_START between @FIRSTMONTH and @LASTMONTH


	--SELECT (SELECT FIRST_NAME FROM EMPLOYEE WHERE EMP_ID = A.FACILITATOR) AS FAC_NAME, (SELECT FIRST_NAME FROM EMPLOYEE WHERE EMP_ID = A.MINUTES_TAKER) AS MIN_NAME, A.*  FROM COMCELL_MEETING A INNER JOIN EMPLOYEE B
	--ON A.EMP_ID = B.EMP_ID
	--WHERE B.DEPT_ID = @DEPTID AND B.DIV_ID = @DIVID AND A.FY_START BETWEEN @FIRSTMONTH AND @LASTMONTH
	--ORDER BY DSPLY_ORDR ASC
END

GO


